# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# conda activate snakemake
# snakemake --use-conda -c60 -k -p

#
import os
import pandas as pd

#os.system("workflow/scripts/download_biosample.sh")


configfile: "config/config.yaml"


samples = pd.read_table(config["samples"])




# ##### Target rules #####

# Define the final output rule

rule all:
   input:
        expand("results/{biosample_ID}/03_{biosample_ID}_megahit_diamond.daa", biosample_ID=samples["samples"]),
        
        




##### Modules #####
include: "rules/fastq_gunzip.smk"
include: "rules/trim.smk"
include: "rules/megahit.smk"
include: "rules/diamond.smk"
#include: "rules/megan_meganizer.smk"
#include: "rules/megan_export.smk"

